# Generated by Django 4.2.6 on 2023-10-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=8)),
                ('complemento', models.CharField(blank=True, max_length=70)),
            ],
        ),
    ]
