# Generated by Django 4.2.6 on 2023-10-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='endereco',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.endereco'),
        ),
    ]
