# Generated by Django 4.2.4 on 2023-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_comentario_autor_doacao_doador_feedback_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='texto',
            field=models.TextField(default='', max_length=300),
        ),
    ]
