# Generated by Django 4.2.7 on 2023-11-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_comentario_autor_doacao_doador_feedback_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceria',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
