# Generated by Django 4.2.4 on 2023-11-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_alter_atracao_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='nome',
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='texto',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
