# Generated by Django 4.2.7 on 2023-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_remove_pessoafisica_cpf_remove_pessoafisica_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='numero',
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='formato',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
