# Generated by Django 4.2.7 on 2023-11-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_remove_evento_numero_evento_endereco_evento_formato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='formato',
            new_name='thumbnail',
        ),
    ]
