# Generated by Django 4.2.6 on 2023-10-31 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_remove_evento_atracao_remove_evento_equipamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='evento',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='atracao',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.atracao'),
        ),
    ]
