# Generated by Django 4.2.6 on 2023-10-31 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_remove_equipamento_evento_equipamento_atracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='texto',
            new_name='equipamento',
        ),
    ]
