# Generated by Django 4.2.6 on 2023-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_rename_texto_equipamento_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
