# Generated by Django 4.2.6 on 2023-11-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0010_evento_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='equipamento',
            new_name='texto',
        ),
    ]
