# Generated by Django 4.2.6 on 2023-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0011_rename_equipamento_equipamento_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='formato',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
