# Generated by Django 4.2.6 on 2023-11-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0014_comentario_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='texto',
            field=models.TextField(max_length=200),
        ),
    ]
